### PR TITLE
add Readme.md file with vercel link

### PR DESCRIPTION
**Pull request by NikolaGolubovic**

### CODE REVIEW

**Comment by ghost** [comment]
image
This section needs to be much smaller. Email validation is required, not just when the input is empty.

**Comment by NikolaGolubovic** [comment]
> image
> This section needs to be much smaller. Email validation is required, not just when the input is empty.

potrudicu se da popravim ovu grozomoriju jer pogresno sam razumeo da sekcija treba da bude preko celog ekrana. ako tesko ide onda radim od pocetka...

**Comment by sandraristic7** [comment]
> > image
> > This section needs to be much smaller. Email validation is required, not just when the input is empty.
> 
> potrudicu se da popravim ovu grozomoriju jer pogresno sam razumeo da sekcija treba da bude preko celog ekrana. ako tesko ide onda radim od pocetka...

**Comment by ghost** [comment]
Ok. Try writing in English. :)

**Pull request merged**
